name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4.2.2"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4.2.2"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  lint_and_test:
    runs-on: ubuntu-latest
    name: Lint, type check, and tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio black isort mypy

      - name: Run black check
        run: black --check --diff .

      - name: Run isort check
        run: isort --profile black --check-only --diff .

      - name: Run mypy
        run: mypy custom_components/duolingo_profile

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
